import { Dimensions, Platform, StyleSheet } from 'react-native'
import NormalizeSize from '../fontScaler/NormalizeSize'
import { RFValue } from 'react-native-responsive-fontsize'
import colors from './Colors'
import { Font_Sizes } from '../fontScaler/fonts'
import spacing from './Spacing'
import { FontStyles } from '../fontScaler/FontStyles'
import borders from './Borders'
import { widthPercentageToDP } from 'react-native-responsive-screen'

const CommonStyles = StyleSheet.create({
  pictureSec: {
    height: NormalizeSize.getFontSize(40),
    width: '100%',
    borderWidth: 2,
    borderRadius: widthPercentageToDP(2),
    borderColor: '#E2E5E9',
    borderStyle: 'dashed',
    flexDirection: 'row',
  },
  companyName: {
    fontSize: Font_Sizes?.large,
    fontFamily: FontStyles.regular,
    color: colors?.blackHeading,
  },
  textInputHeading: {
    fontFamily: FontStyles.regular,
    fontSize: Font_Sizes.medium,
    lineHeight: NormalizeSize.getFontSize(20),
    color: '#212529',
    // paddingBottom: NormalizeSize.getFontSize(5),
  },
  emptyComponentContainer: {
    paddingHorizontal: spacing?.large,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    height: Dimensions.get('screen').height / 1.5,
  },
  emptyComponent: {
    color: '#9FA3A9',
    padding: 9,
    fontSize: Font_Sizes.medium,
    fontFamily: FontStyles.regular,
  },
  mainView: {
    width: '100%',
    height: NormalizeSize.getFontSize(72),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: widthPercentageToDP(2),
  },
  headingContainer: {
    width: '93%',
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: spacing.large18,
    height: NormalizeSize.getFontSize(20),
    justifyContent: 'space-between',
    marginTop: spacing.medium,
  },
  marginhorizontal: {
    flexGrow: 1,
    paddingHorizontal: RFValue(16),
  },
  heading: {
    fontFamily: FontStyles.semiBold,
    textAlign: 'left',
    fontSize: Font_Sizes.large,
    paddingLeft: RFValue(2),
    // lineHeight: RFValue(20),
    color: colors.black,
  },
  subHeadingContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingBottom: spacing.xxmedium,
    marginVertical: spacing.medium,
  },
  breadCrumHeading: {
    fontSize: Font_Sizes.large,
    lineHeight: RFValue(20),
    // paddingBottom: RFValue(8),
    fontFamily: FontStyles.regular,
    color: colors.dark,
    textAlign: 'left',
  },
  textInput: {
    fontFamily: FontStyles.regular,
    width: '80%',
    height: RFValue(40),
    // top: RFValue(2.5),
    fontSize: Font_Sizes.medium,
  },
  searchContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: RFValue(10),
  },
  clearAll: {
    fontSize: Font_Sizes.large,
    fontFamily: Platform.OS == 'ios' ? FontStyles.medium : FontStyles.regular,
    justifyContent: 'center',
    alignItems: 'center',
    color: colors.iconColor,
  },
  textInputHeading: {
    fontFamily: FontStyles.regular,
    fontSize: Font_Sizes.medium,
    lineHeight: NormalizeSize.getFontSize(20),
    color: colors.blackHeading,
    paddingBottom: NormalizeSize.getFontSize(5),
  },
  formTextInput: {
    backgroundColor: colors.inputBackground,
    borderRadius: borders.radius.medium.borderRadius,
    fontFamily: FontStyles.regular,
    textAlignVertical: 'center',
    margin: 0,
    padding: 0,
    height: RFValue(36),
    fontSize: Font_Sizes.medium,
    paddingHorizontal: RFValue(12),
    lineHeight: Platform.OS === 'ios' ? 0 : spacing.large20,
    color: colors.blackHeading,
  },
  formTextInputErrorValidation: {
    fontSize: NormalizeSize.getFontSize(13),
    color: colors.error,
    // lineHeight: NormalizeSize.getFontSize(20),
    marginTop: NormalizeSize.getFontSize(6),
    fontFamily: FontStyles.regular,
  },
  formTextInputError: {
    backgroundColor: colors.inputBackground,
    borderRadius: borders.radius.medium.borderRadius,
    borderWidth: 1,
    borderColor: colors.error,
    // marginBottom: RFValue(12),
    fontFamily: FontStyles.regular,
    textAlignVertical: 'center',
    margin: 0,
    padding: 0,
    height: RFValue(36),
    fontSize: Font_Sizes.medium,
    paddingHorizontal: RFValue(16),
    lineHeight: RFValue(20),
    color: colors.error,
  },
  formTextInputIcon: {
    position: 'absolute',
    height: RFValue(36),
    // bottom: spacing.large,
    alignItems: 'center',
    justifyContent: 'center',
    right: 15,
  },
  placeholderStyle: {
    fontSize: Font_Sizes.medium,
    // bottom: RFValue(2),
    fontFamily: FontStyles.regular,
    color: colors.iconColor,
  },
  placeholderStyleError: {
    fontSize: RFValue(14),
    bottom: RFValue(2),
    color: colors.error,
  },
  selectedTextStyle: {
    fontSize: Font_Sizes.medium,
    fontFamily: 'NunitoSans-Regular',
    color: '#212529',
  },
  containerStyle: {
    borderRadius: widthPercentageToDP(2),
    backgroundColor: '#ffff',
    position: 'static',
    marginTop: 5,
    padding: 2,
    shadowColor: '#fffff',
    // shadowOpacity: 0.9,
    // elevation: 0.6,
    //  shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: Platform.OS === 'ios' ? 0.5 : 0.1,
    shadowRadius: Platform.OS === 'ios' ? 0.2 : 7,
    elevation: Platform.OS === 'ios' ? 1 : 0.5,
    // borderBottomWidth: 0.5,
    // borderRadius: RFValue(8),
    // borderWidth: 0.5,
    // backgroundColor: colors.white,
    // marginTop: 5,
    // shadowColor: colors.white,
    // shadowOpacity: 0.9,
    // elevation: 0.6,
  },
  itemContainerStyle: {
    fontSize: Font_Sizes.medium,
    backgroundColor: colors.white,
    borderRadius: widthPercentageToDP(2),
    // borderBottomWidth: 1,
    // borderBottomColor: '#F1F2F3',
  },
  DropdownListItem: {
    padding: 9,
    fontSize: Font_Sizes.medium,
    fontFamily: FontStyles.semiBold,
    color: '#212529',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F2F3',
    backgroundColor: '#ffffff',
    // flexDirection: 'row',
    // paddingHorizontal: RFValue(14),
    // paddingVertical: RFValue(6),
    // borderRadius: RFValue(8),
  },
  dropdownListTextItem: {
    fontSize: Font_Sizes.medium,
    width: '100%',
    fontFamily: FontStyles.regular,
    // padding: widthPercentageToDP(1),
    borderRadius: RFValue(8),
    paddingLeft: RFValue(6),
    color: colors.blackHeading,
  },
  iconStyle: {
    width: 20,
    height: 20,
    color: '#9FA3A9',
  },
  remarkTextInput: {
    backgroundColor: colors.inputBackground,
    borderRadius: RFValue(8),
    // marginBottom: RFValue(12),
    fontFamily: FontStyles.regular,
    textAlignVertical: 'top',
    margin: 0,
    padding: 0,
    height: RFValue(120),
    fontSize: Font_Sizes.medium,
    paddingHorizontal: RFValue(16),
    paddingVertical: RFValue(8),
    lineHeight: RFValue(20),
    color: colors.blackHeading,
  },
  remarkTextInputError: {
    backgroundColor: colors.inputBackground,
    // marginBottom: RFValue(12),
    fontFamily: FontStyles.regular,
    textAlignVertical: 'top',
    margin: 0,
    padding: 0,
    height: RFValue(120),
    fontSize: Font_Sizes.medium,
    paddingHorizontal: RFValue(16),
    paddingVertical: RFValue(8),
    lineHeight: RFValue(20),
    borderRadius: borders.radius.medium.borderRadius,
    borderWidth: 1,
    borderColor: colors.error,
    color: colors.blackHeading,
  },
  separatorContainer: {
    marginVertical: spacing.large,
    alignItems: 'center',
  },
  separator: {
    height: 1,
    width: '25%',
    backgroundColor: colors.greyE2E5E9,
  },
  addItem: {
    color: colors.blueButton,
    height: RFValue(17),
    paddingLeft: RFValue(8),
    fontFamily: FontStyles.regular,
    fontSize: Font_Sizes.medium,
    // paddingBottom: RFValue(4),
    textAlignVertical: 'center',
  },
  showDropdownViewContainer: {
    // maxHeight: NormalizeSize.getFontSize(155),
    backgroundColor: colors.white,
    marginBottom: RFValue(2),
    marginTop: 6,
    borderRadius: 8,
    shadowColor: '#000',
    borderTopWidth: 1,
    borderTopColor: colors.lightGrey,
    borderLeftWidth: Platform.OS == 'ios' ? 1 : 0,
    borderLeftColor: Platform.OS == 'ios' ? colors.lightGrey : '',
    shadowOffset: {
      width: Platform.OS == 'ios' ? 0.2 : 0,
      height: Platform.OS == 'ios' ? 0.2 : 0,
    },
    shadowOpacity: 0.4,
    shadowRadius: Platform.OS === 'ios' ? 0 : 7,
    elevation: 1,
  },
  showDropdownTouchable: {
    height: 40,
    paddingHorizontal: 11,
    marginHorizontal: NormalizeSize.getFontSize(8),
    borderBottomWidth: 1,
    borderBottomColor: '#F1F2F3',
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.12)',
  },
  modalContent: {
    width: '95%',
    height: Dimensions.get('screen').height * 0.51,
    // height: '50%',
    backgroundColor: colors.white,
    paddingVertical: spacing.large,
    // height: Dimensions.get('screen').height*0.368,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 6,
    borderColor: 'rgb(255, 255, 255)',
  },
  closeButtonView: {
    width: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
    borderTopWidth: 1,
    paddingTop: spacing.medium,
    borderTopColor: colors.greyE2E5E9,
  },
  closeButtonTouch: {
    justifyContent: 'center',
    alignItems: 'center',
    // paddingVertical: 6,
    paddingHorizontal: 12,
  },
  closeButtonText: {
    fontFamily: FontStyles.regular,
    // margin: 6,
    fontSize: Font_Sizes.large,
    color: '#005BA9',
  },
  nextText: {
    fontFamily: FontStyles.regular,
    fontSize: Font_Sizes.large,
    color: colors.blackHeading,
  },
  badge: {
    backgroundColor: '#F9F9FA',
    borderRadius: 1000,
    justifyContent: 'center',
    height: spacing?.xlarge,
  },
  badgeText: {
    color: '#61666A',
    fontSize: Font_Sizes?.smaller,
    fontFamily: FontStyles.semiBold,
    marginHorizontal: 8,
  },
  ballView: {
    height: spacing.small6,
    width: spacing.small6,
    borderRadius: 3,
    backgroundColor: colors.darkGreen,
    marginRight: 4,
    marginLeft: 8,
  },
  absoluteChipView: {
    position: 'absolute',
    height: spacing.xlarge,
    right: 10,
    // top: 8,
    backgroundColor: colors.greentagBackground,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    padding: 2,
  },
  newChipText: {
    color: colors.darkGreen,
    fontSize: spacing.xxmedium,
    textAlignVertical: 'center',
    marginLeft: 4,
    marginRight: 8,
    fontFamily: FontStyles.semiBold,
  },
  elementDropdown:{
    fontFamily: FontStyles?.semiBold,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E5E9',
    // backgroundColor: '#fff',
    // height: RFValue(40),
    // padding: RFValue(4),
    borderRadius: spacing?.small,
    paddingHorizontal: RFValue(10),
    fontSize: RFValue(14),
    // lineHeight: RFValue(16),
    color: '#212529',
    paddingVertical: RFValue(4),
  },
  elementPlaceholderStyle: {
    fontSize: RFValue(14),
    color: '#212529',
  },
  elementSelectedTextStyle:{
    fontFamily: 'NunitoSans-Regular',
    fontSize: RFValue(14),
    lineHeight: RFValue(20),
    color: '#212529',
  },
  elementDropdownEditContainer:{
    borderRadius: spacing?.small,
    right: spacing?.large28,
    width: 140,
    padding: 0,
    // height: 100,
  },
  elementItemContainerStyle:{
    borderBottomColor: '#E2E6E6',
    borderBottomWidth: 0.5,
    alignItems: 'flex-start',
    justifyContent: 'center',
    // height: 30,
  }
})

export default CommonStyles
